[case]
;测试的是读服务器，还是写服务器；读为read，写为write
server=read
;是否上传并解压压测文件(新增测试镜像文件，暂时未加)，1为是，0为否;建议首次上传后改为0
upload=1
;是否进行基础环境安装，1为是，0为否;建议首次安装后改为0
install=1
;是否进行网卡基准测试环境，1为是，0为否;建议首次运行后改为0
test_net=0
;是否进行磁盘基准测试环境，1为是，0为否;建议首次运行后改为0
test_disk=0
;磁盘基准测试路径;
data_path=/dev/mapper/mpatha
disk_path=/dev/mapper/mpathb
writeback_path=/dev/mapper/mpathc
;基准测试数据磁盘大小;单位TB
test_datadisk_size=57.3
;是否进行capture压测做包，1为是，0为否；建议首次运行后改为0
make_package=0
;是否进行capture压测，1为是，0为否；安装环境和做包后，可以单独运行压测，节约时间；
run_capture=0

;以下为被压测服务器；hostname为自定义主机名，供zabbix监控使用；
[ssh1]
bar_num=0
hostname=server45
host=172.17.7.45
port=22
username=root
password=abc#123
timeout=1.0

;以下为capture服务器，ssh必须按序号顺延；bar_num为网吧数量（单网吧1020终端）；hostname为自定义主机名，供zabbix监控使用；
[ssh2]
bar_num=1
hostname=server130
host=192.168.15.130
port=22
username=root
password=abc#123
timeout=1.0

[ssh3]
bar_num=2
hostname=server131
host=192.168.15.131
port=22
username=root
password=abc#123
timeout=1.0
